### ISSUE TITLE
Example doesn't seem to validate

### ISSUE THREAD

**Issue by meekrosoft** [CircleCI-Public/Orb-Project-Template#21]
## Orb version: 2.1

Cloned this repo and attempted to pack and validate

## What happened:

![image](https://user-images.githubusercontent.com/145429/110604265-29196e80-8188-11eb-8df9-78f33614df60.png)

## Expected behavior:

It should validate successfully

**Comment by gmemstr** [comment]
Rather than `config pack`, we've moved to `orb pack`, which includes support for the `<<include()>>` syntax :)

**Comment by meekrosoft** [comment]
Thanks for the response @gmemstr - that was the solution I was looking for.  I'm going to paste in raw text here in case anyone else googles for this problem. 

```
Error: Error calling command: 'greet'
Unclosed '<<' tag in string: '<<include(scripts/greet.sh)>>'
('<<' must be escaped as '\<<' in config v2.1+)
Error calling job: 'hello'
Error calling command: 'greet'
Unclosed '<<' tag in string: '<<include(scripts/greet.sh)>>'
('<<' must be escaped as '\<<' in config v2.1+)
```

Might is be a good idea to mention the build steps in the `README.md` in the project root?

**Comment by gmemstr** [comment]
Didn't realise we didn't include steps for that! Our bad - will resolve this :)

**Comment by wind57** [comment]
I hit a similar problem in `config.yaml`:

```
jobs:
  test:
    machine: true
    steps:
      - checkout
      - run:
          name: Run regular tests
          command: |
                CLASSNAMES=....
                read -a NON_NESTED_CLASSNAMES_ARRAY <<< CLASSNAMES
   .....
```

This fails with ` ('<<' must be escaped as '\\<<' in config v2.1+)`. How do I solve this?
