### ISSUE TITLE
allow include python script 

### ISSUE THREAD

**Issue by adecchi-2inno** [CircleCI-Public/Orb-Project-Template#25]
## Describe Request:
Allow to execute python script command like actually do with bash. 

## Example:
`
parameters:
  to:
    type: string
    default: "World"
    description: "Hello to whom?"
steps:
  - run:
      environment:
        PARAM_TO: <<parameters.to>>
      name: Hello Greeting
      command: <<include(scripts/greet.py)>>
`

**Comment by felixshiftellecon** [comment]
I know this is an older issue but wanted to mention that python scripts can be used with include by setting the shell environment to python.

```
steps:
  - run:
      name: Python Greeting
      shell: /usr/bin/env python3
      command: <<include(scripts/greet.py)>>
```
