### ISSUE TITLE
Enhancement: Provide shell example in README.md

### ISSUE THREAD

**Issue by Jaryt** [CircleCI-Public/Orb-Project-Template#35]
Provide a comment on shell usage for different languages in scripts/README.md: https://github.com/CircleCI-Public/Orb-Project-Template/tree/master/src/scripts

ex:

```
steps:
  - run:
      environment:
        PARAM_TO: <<parameters.to>
      name: Hello <<parameters.to>
      shell: /bin/sh  # Not required for shell scripts, but useful for other shell environments i.e. python
      command: <<include(scripts/greet.sh)>>
```

This would help users who may expect the included script to execute without declaring the shell parameter: https://github.com/CircleCI-Public/Orb-Project-Template/issues/25
